/** The kit's own strings. Every other visible string reaches a kit component as an already-translated prop. */
export const kitLanguages = [
  "en",
  "es",
  "fr",
  "de",
  "it",
  "pt",
  "nl",
  "sv",
  "ja",
  "ko",
  "zh",
] as const;
export type KitLanguage = (typeof kitLanguages)[number];

const en = {
  cancel: "Cancel",
  done: "Done",
  save: "Save",
  close: "Close",
  undo: "Undo",
  retry: "Retry",
  back: "Back",
  more: "More",
  search: "Search",
  clearSearch: "Clear search",
  selected: "Selected",
  loading: "Loading…",
  processing: "Saving…",
  noData: "No data",
  over: "over",
  goal: "Goal",
  /** Chart range: the whole history (RangeChips). */
  all: "All",
  increase: "Increase",
  decrease: "Decrease",
  /** Unit symbols with no ECMA-402 unit (milligram), or when Intl unit output is untrusted (Hermes on iOS). */
  unitGram: "g",
  unitMilligram: "mg",
  /** List fallbacks when Intl.ListFormat is missing (Hermes): the last two items, and between the others. */
  listAnd: "{0} and {1}",
  listOr: "{0} or {1}",
  listSeparator: ", ",
};
export type KitStringKey = keyof typeof en;
export type KitStrings = Record<KitStringKey, string>;

export const kitStrings = {
  en,
  es: {
    cancel: "Cancelar",
    done: "Listo",
    save: "Guardar",
    close: "Cerrar",
    undo: "Deshacer",
    retry: "Reintentar",
    back: "Atrás",
    more: "Más",
    search: "Buscar",
    clearSearch: "Borrar búsqueda",
    selected: "Seleccionado",
    loading: "Cargando…",
    processing: "Guardando…",
    noData: "Sin datos",
    over: "de más",
    goal: "Objetivo",
    all: "Todo",
    increase: "Aumentar",
    decrease: "Disminuir",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} y {1}",
    listOr: "{0} o {1}",
    listSeparator: ", ",
  },
  fr: {
    cancel: "Annuler",
    done: "OK",
    save: "Enregistrer",
    close: "Fermer",
    undo: "Annuler l’action",
    retry: "Réessayer",
    back: "Retour",
    more: "Plus",
    search: "Rechercher",
    clearSearch: "Effacer la recherche",
    selected: "Sélectionné",
    loading: "Chargement…",
    processing: "Enregistrement…",
    noData: "Aucune donnée",
    over: "en trop",
    goal: "Objectif",
    all: "Tout",
    increase: "Augmenter",
    decrease: "Diminuer",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} et {1}",
    listOr: "{0} ou {1}",
    listSeparator: ", ",
  },
  de: {
    cancel: "Abbrechen",
    done: "Fertig",
    save: "Sichern",
    close: "Schließen",
    undo: "Widerrufen",
    retry: "Erneut versuchen",
    back: "Zurück",
    more: "Mehr",
    search: "Suchen",
    clearSearch: "Suche löschen",
    selected: "Ausgewählt",
    loading: "Wird geladen…",
    processing: "Wird gesichert…",
    noData: "Keine Daten",
    over: "zu viel",
    goal: "Ziel",
    all: "Alle",
    increase: "Erhöhen",
    decrease: "Verringern",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} und {1}",
    listOr: "{0} oder {1}",
    listSeparator: ", ",
  },
  it: {
    cancel: "Annulla",
    done: "Fine",
    save: "Salva",
    close: "Chiudi",
    undo: "Annulla azione",
    retry: "Riprova",
    back: "Indietro",
    more: "Altro",
    search: "Cerca",
    clearSearch: "Cancella ricerca",
    selected: "Selezionato",
    loading: "Caricamento…",
    processing: "Salvataggio…",
    noData: "Nessun dato",
    over: "in eccesso",
    goal: "Obiettivo",
    all: "Tutto",
    increase: "Aumenta",
    decrease: "Diminuisci",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} e {1}",
    listOr: "{0} o {1}",
    listSeparator: ", ",
  },
  pt: {
    cancel: "Cancelar",
    done: "OK",
    save: "Salvar",
    close: "Fechar",
    undo: "Desfazer",
    retry: "Tentar novamente",
    back: "Voltar",
    more: "Mais",
    search: "Buscar",
    clearSearch: "Limpar busca",
    selected: "Selecionado",
    loading: "Carregando…",
    processing: "Salvando…",
    noData: "Sem dados",
    over: "acima",
    goal: "Meta",
    all: "Tudo",
    increase: "Aumentar",
    decrease: "Diminuir",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} e {1}",
    listOr: "{0} ou {1}",
    listSeparator: ", ",
  },
  nl: {
    cancel: "Annuleer",
    done: "Gereed",
    save: "Bewaar",
    close: "Sluit",
    undo: "Herstel",
    retry: "Probeer opnieuw",
    back: "Terug",
    more: "Meer",
    search: "Zoek",
    clearSearch: "Wis zoekopdracht",
    selected: "Geselecteerd",
    loading: "Laden…",
    processing: "Bewaren…",
    noData: "Geen gegevens",
    over: "te veel",
    goal: "Doel",
    all: "Alles",
    increase: "Verhoog",
    decrease: "Verlaag",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} en {1}",
    listOr: "{0} of {1}",
    listSeparator: ", ",
  },
  sv: {
    cancel: "Avbryt",
    done: "Klar",
    save: "Spara",
    close: "Stäng",
    undo: "Ångra",
    retry: "Försök igen",
    back: "Tillbaka",
    more: "Mer",
    search: "Sök",
    clearSearch: "Rensa sökning",
    selected: "Vald",
    loading: "Läser in…",
    processing: "Sparar…",
    noData: "Inga data",
    over: "över",
    goal: "Mål",
    all: "Allt",
    increase: "Öka",
    decrease: "Minska",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} och {1}",
    listOr: "{0} eller {1}",
    listSeparator: ", ",
  },
  ja: {
    cancel: "キャンセル",
    done: "完了",
    save: "保存",
    close: "閉じる",
    undo: "取り消す",
    retry: "再試行",
    back: "戻る",
    more: "その他",
    search: "検索",
    clearSearch: "検索をクリア",
    selected: "選択済み",
    loading: "読み込み中…",
    processing: "保存中…",
    noData: "データなし",
    over: "超過",
    goal: "目標",
    all: "全期間",
    increase: "増やす",
    decrease: "減らす",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0}、{1}",
    listOr: "{0}または{1}",
    listSeparator: "、",
  },
  ko: {
    cancel: "취소",
    done: "완료",
    save: "저장",
    close: "닫기",
    undo: "실행 취소",
    retry: "다시 시도",
    back: "뒤로",
    more: "더 보기",
    search: "검색",
    clearSearch: "검색어 지우기",
    selected: "선택됨",
    loading: "불러오는 중…",
    processing: "저장 중…",
    noData: "데이터 없음",
    over: "초과",
    goal: "목표",
    all: "전체",
    increase: "늘리기",
    decrease: "줄이기",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0} 및 {1}",
    listOr: "{0} 또는 {1}",
    listSeparator: ", ",
  },
  zh: {
    cancel: "取消",
    done: "完成",
    save: "保存",
    close: "关闭",
    undo: "撤销",
    retry: "重试",
    back: "返回",
    more: "更多",
    search: "搜索",
    clearSearch: "清除搜索",
    selected: "已选择",
    loading: "正在载入…",
    processing: "正在保存…",
    noData: "无数据",
    over: "超出",
    goal: "目标",
    all: "全部",
    increase: "增加",
    decrease: "减少",
    unitGram: "g",
    unitMilligram: "mg",
    listAnd: "{0}和{1}",
    listOr: "{0}或{1}",
    listSeparator: "、",
  },
} satisfies Record<KitLanguage, KitStrings>;
